# Dependencies
markdown:         redcarpet
highlighter:      rouge
gems:             [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Alexander Savi
tagline:          ''
description:      'PhD candidate at <a href="http://psyres.uva.nl/research/content/programme-group-psychological-methods/programme-group-psychological-methods.html" target="_blank">UvA Psychological Methods</a>, studying (online) learning and psychometrics.'
url:              https://github.com/aosavi/hyde/
baseurl:          http://aosavi.github.io/hyde/

author:
  name:           'Alexander Savi'
  url:            https://twitter.com/alexandersavi

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/poole/hyde