# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        /blog/:title/

# Setup
title:            Alexander Savi
tagline:          ''
description:      'Psychological methods, learning & education, adaptive practice, cognitive development, a/b testing.'
url:              https://aosavi.github.io
baseurl:          
baseurlknitr:     /

author:
  name:           'Alexander Savi'
  email:          o.a.savi@gmail.com
  url:            https://twitter.com/alexandersavi

paginate:         25
paginate_path:    "blog/page:num/"
blog_path:        "blog/"

future:           true

# Custom vars
version:          0.1.2

github:
  repo:           https://github.com/aosavi/aosavi.github.io
